steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/browser-automation-app', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/browser-automation-app']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'browser-automation-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/browser-automation-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--port'
      - '5000'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PRODUCTION=true'

# Set a longer timeout as browser installation might take time during the build
timeout: 1800s

images:
  - 'gcr.io/$PROJECT_ID/browser-automation-app'